### PR TITLE
NEW MAJOR VERSION is Required 

### PR DESCRIPTION
**Pull request by Legion112**
Update kevinrob/guzzle-cache-middleware to ~4.0

### CODE REVIEW

**Comment by Legion112** [comment]
@gregurco tag [2.3 ](https://github.com/gregurco/GuzzleBundleCachePlugin/releases/tag/v2.3.0)have to be **deleted**.
New **major** version have to be released 3.0.0
I have pointed in Mr request with Uppercase laters `NEW MAJOR VERSION is Required`

It's a backwoods comfortability break. 
image

**Comment by simonberger** [comment]
The release is still available in packagist. Regarding backward incompatibility just the cache invalidation is relevant right?
If this is seen critical I would recommend to release a 2.3.1 patch release to revert the change there.

**Comment by gregurco** [comment]
@simonberger thank you for the information. I removed release 2.3 from packagist.
I don't see the reason to create release 2.3.1.

**Comment by simonberger** [comment]
@gregurco thanks, I also think this is good enough here, because it was a relative short time available and the breaking change should not be that critical.
Generally there are good reasons why a new tag is necessary. There is no defined process for a removal of a packagist release and it can never be erased completely. My company for example uses a proxy package management system and will never forget the once "learned" 2.3.0 release.

**Pull request merged**
