### PR TITLE
Add NullEventDispatcher

### PR DESCRIPTION
**Pull request by Neirda24**
Add the `NullEventDispatcher` class. It allows us to inject the event_dispctaher even though the config is not enabled.

### CODE REVIEW

**Comment by gregurco** [comment]
@Neirda24 I didn't notice that, but could you please explain me, why did you create our own event dispatcher and didn't use `@event_dispatcher` from symfony? In this case we can avoid this problem, I guess...

**Comment by Neirda24** [comment]
@gregurco : We cannot use the `event_dispatcher` from symfony because in the `InvalidateRequestSubscriber` needs to have access to the storage strategy (through the cache middleware). From one request and/or guzzle client we would require to be able to fetch its cache middleware. But we can't :/ . So the only solution I found so far was to create one event_dispatcher per client (we are restraining the scope).

So if you used the event_dispatcher form symfony I guess yes it would be avoided...

**Comment by gregurco** [comment]
@Neirda24 probably. I will try to allocate time today/tomorrow and will try to use event dispatcher from symfony. If it will work then the code will be much more simplier if no then I will merge your request.

**Comment by Neirda24** [comment]
Of course. Not a problem. Keep me posted. Thanks

**Comment by gregurco** [comment]
Close this PR. Changes are made in #7 . Thank you @Neirda24 for idea and review :+1:

**Pull request closed without merging**
